version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    # volumes:
    #   - ./stonksexchange-checker-db:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: enoislove
    #   MONGO_INITDB_ROOT_PASSWORD: enoislife1338