version: '3'
services:
  n0t3b00k:
    # Our Dockerfile is in the current folder.
    build: .
    # Mount the data folder writable, so that information can be persisted across restarts.
    volumes:
      - ./data/:/data:rw
    # Define the port mapping (external:internal port)
    ports:
      - "2323:8000"
